# Music Monitor
output DP-2 resolution 1920x1080 position 0,360
# Main Monitor
output DP-1 resolution 2560x1440 position 1920,0
# Third Monitor
output DP-3 resolution 1920x1080 position 4480,360

# Drawing monitor
output HDMI-A-1 resolution 1920x1080 position 6400,360

output * bg ~/Wallpapers/mountain-night-wallpaper.jpg fill
